# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - task: test:{{.TYPE}}
    vars:
      TYPE: '{{default "unit" .CLI_ARGS}}'
  test:e2e:
    dir: tests/e2e
    cmds:
      - npx cypress open

  setup-backend:
    cmds:
      - uv sync
  setup-frontend:
    cmds:
      - npm install

  backend:
    dir: server
    cmds:
      - uv run manage.py runserver
  frontend:
    cmds:
      - npm run dev

  setup:
    deps:
      - setup-backend
      - setup-frontend

  dev:
    deps:
      - backend
      - frontend
    parallel: true
