# https://taskfile.dev

version: '3'

tasks:
  backend:
    cmds:
      - uv run server/manage.py runserver
  frontend:
    cmds:
      - cd client && npm run dev
  dev:
    deps:
      - backend
      - frontend
    parallel: true
