# https://taskfile.dev

version: "3"

tasks:
  setup-backend:
    # dir: server
    cmds:
      - uv sync
  setup-frontend:
    cmds:
      - npm install
  backend:
    dir: server
    cmds:
      - uv run manage.py runserver
  frontend:
    cmds:
      - npm run dev
  setup:
    deps:
      - setup-backend
      - setup-frontend
  dev:
    deps:
      - backend
      - frontend
    parallel: true
