# Generated by Django 5.2.7 on 2025-10-26 21:42

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("api", "0003_remove_transportservice_price"),
	]

	operations = [
		migrations.RemoveField(
			model_name="transportservice",
			name="name",
		),
	]
