# Generated by Django 5.2.7 on 2025-10-26 21:44

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("api", "0004_remove_transportservice_name"),
	]

	operations = [
		migrations.RemoveField(
			model_name="enrollment",
			name="total_price",
		),
	]
