# Generated by Django 5.2.7 on 2025-10-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("api", "0005_remove_enrollment_total_price"),
	]

	operations = [
		migrations.AlterField(
			model_name="user",
			name="document_id",
			field=models.CharField(blank=True, max_length=50, null=True, unique=True),
		),
	]
